-- Lo schema non sta piu' qui.
--
-- Vive in supabase/migrations/, un file numerato per volta, applicati in ordine crescente.
-- Istruzioni: supabase/README.md. Il perche': docs/adr/002-migrazioni-numerate.md.
--
-- Questo file conteneva tutto lo schema in un blocco solo, e prometteva di ricreare il
-- backend da zero. Non ci riusciva: si fermava a meta' (una policy su ride_comments prima
-- che la tabella esistesse) e conteneva due volte lo stesso blocco, quindi nemmeno si
-- poteva rilanciare. Le migrazioni fanno le due cose, e la CI lo verifica a ogni push.
--
-- Per sapere quale schema e' applicato adesso, dal SQL editor di Supabase:
--   select version, applied_at from public.schema_migrations order by version;
